package com.cheer.dao;

import com.cheer.domain.Board;

public interface BoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer boardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    int insert(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    int insertSelective(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    Board selectByPrimaryKey(Integer boardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Board record);
}