package com.cheer.domain;

import java.io.Serializable;

public class Blog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogid
     *
     * @mbg.generated
     */
    private Integer blogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.theme
     *
     * @mbg.generated
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.text
     *
     * @mbg.generated
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogtime
     *
     * @mbg.generated
     */
    private String blogtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.useravatar
     *
     * @mbg.generated
     */
    private String useravatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.sumbd
     *
     * @mbg.generated
     */
    private Integer sumbd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogid
     *
     * @return the value of blog.blogid
     *
     * @mbg.generated
     */
    public Integer getBlogid() {
        return blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogid
     *
     * @param blogid the value for blog.blogid
     *
     * @mbg.generated
     */
    public void setBlogid(Integer blogid) {
        this.blogid = blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.theme
     *
     * @return the value of blog.theme
     *
     * @mbg.generated
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.theme
     *
     * @param theme the value for blog.theme
     *
     * @mbg.generated
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.text
     *
     * @return the value of blog.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.text
     *
     * @param text the value for blog.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogtime
     *
     * @return the value of blog.blogtime
     *
     * @mbg.generated
     */
    public String getBlogtime() {
        return blogtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogtime
     *
     * @param blogtime the value for blog.blogtime
     *
     * @mbg.generated
     */
    public void setBlogtime(String blogtime) {
        this.blogtime = blogtime == null ? null : blogtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.username
     *
     * @return the value of blog.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.username
     *
     * @param username the value for blog.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.useravatar
     *
     * @return the value of blog.useravatar
     *
     * @mbg.generated
     */
    public String getUseravatar() {
        return useravatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.useravatar
     *
     * @param useravatar the value for blog.useravatar
     *
     * @mbg.generated
     */
    public void setUseravatar(String useravatar) {
        this.useravatar = useravatar == null ? null : useravatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.sumbd
     *
     * @return the value of blog.sumbd
     *
     * @mbg.generated
     */
    public Integer getSumbd() {
        return sumbd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.sumbd
     *
     * @param sumbd the value for blog.sumbd
     *
     * @mbg.generated
     */
    public void setSumbd(Integer sumbd) {
        this.sumbd = sumbd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Blog other = (Blog) that;
        return (this.getBlogid() == null ? other.getBlogid() == null : this.getBlogid().equals(other.getBlogid()))
            && (this.getTheme() == null ? other.getTheme() == null : this.getTheme().equals(other.getTheme()))
            && (this.getText() == null ? other.getText() == null : this.getText().equals(other.getText()))
            && (this.getBlogtime() == null ? other.getBlogtime() == null : this.getBlogtime().equals(other.getBlogtime()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getUseravatar() == null ? other.getUseravatar() == null : this.getUseravatar().equals(other.getUseravatar()))
            && (this.getSumbd() == null ? other.getSumbd() == null : this.getSumbd().equals(other.getSumbd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBlogid() == null) ? 0 : getBlogid().hashCode());
        result = prime * result + ((getTheme() == null) ? 0 : getTheme().hashCode());
        result = prime * result + ((getText() == null) ? 0 : getText().hashCode());
        result = prime * result + ((getBlogtime() == null) ? 0 : getBlogtime().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getUseravatar() == null) ? 0 : getUseravatar().hashCode());
        result = prime * result + ((getSumbd() == null) ? 0 : getSumbd().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", blogid=").append(blogid);
        sb.append(", theme=").append(theme);
        sb.append(", text=").append(text);
        sb.append(", blogtime=").append(blogtime);
        sb.append(", username=").append(username);
        sb.append(", useravatar=").append(useravatar);
        sb.append(", sumbd=").append(sumbd);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}